name: Generate Documentation Website

on:
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install NPM Packages
        run: bun install; bun install next react react-dom; bun i bun-doc -g
      - name: Clean the Package
        run: rm -f ./tsconfig.json; rm -rf ./docs
      - name: Build
        run: bun-doc build; bunx next build && bunx next export; mv ./out ./docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
